services:
  sn-postgres:
    container_name: sn-postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - ./sn-auth/.env
    ports:
      - "5432:5432"
    restart: unless-stopped

  sn-auth:
    container_name: sn-auth
    build:
      context: ./sn-auth
      dockerfile: Dockerfile
    volumes:
      - ./sn-auth/logs:/logs
    env_file:
      - ./sn-auth/.env
    ports:
      - "8089:8089"
    depends_on:
      - sn-postgres
    restart: unless-stopped

volumes:
  pg-data: