services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  sn-auth:
    container_name: sn-auth
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-data:




#volumes:
#  volume1:
#services:
#  kafka1:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - "9095:9094"
#    environment:
#      - KAFKA_CFG_BROKER_ID=1
#      - KAFKA_CFG_NODE_ID=1
#      - KAFKA_ENABLE_KRAFT=yes
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=1
#
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
#
#      - KAFKA_CFG_LISTENERS=INTERNAL://kafka1:9092,OUTSIDE://kafka1:9094,CONTROLLER://kafka1:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,OUTSIDE://localhost:9095
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
#    volumes:
#      - volume1:/bitnami/kafka1
#  kafka2:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - "9096:9094"
#    environment:
#      - KAFKA_CFG_BROKER_ID=2
#      - KAFKA_CFG_NODE_ID=2
#      - KAFKA_ENABLE_KRAFT=yes
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=1
#
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
#
#
#      - KAFKA_CFG_LISTENERS=INTERNAL://kafka2:9092,OUTSIDE://kafka2:9094,CONTROLLER://kafka2:9093
#      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka2:9092,OUTSIDE://localhost:9096
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
#    volumes:
#      - volume1:/bitnami/kafka2
#  kafka3:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - "9097:9094"
#    environment:
#      - KAFKA_CFG_BROKER_ID=3
#      - KAFKA_CFG_NODE_ID=3
#      - KAFKA_ENABLE_KRAFT=yes
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_KRAFT_CLUSTER_ID=1
#
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
#
#
#      - KAFKA_CFG_LISTENERS=INTERNAL://kafka3:9092,OUTSIDE://kafka3:9094,CONTROLLER://kafka3:9093
#      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka3:9092,OUTSIDE://localhost:9097
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka:9093
#    volumes:
#      - volume1:/bitnami/kafka3
#  ui:
#    image: provectuslabs/kafka-ui:v0.4.0
#    ports:
#      - "8080:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
#      - KAFKA_CLUSTERS_0_NAME=kraft